### ISSUE TITLE
Issues with generator script on Windows 10

### ISSUE THREAD

**Issue by Niosquare** [settinger/selectric_typeballs#2]
Hello! I am running this on Windows, with all the pre-requisites met. I am running this on Python 3.11.3. I know nothing about Python, so I did try to fix some stuff through solutions I found online. The first issue I had was with line 39, where I was met with the following:

`Generating glyph 1...
Traceback (most recent call last):
  File "C:\selectric_typeballs-main\selectric_generator.py", line 39, in <module>
    subprocess.run(cmd)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\chris\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

I was able to fix this, by adding this to line 40:
` subprocess.run(cmd, shell=True)`
Then, after that, I encountered the following when trying to run it: 
`Generating glyph 1...
Traceback (most recent call last):
  File "F:\Downloads (mom)\selectric_typeballs-main\selectric_typeballs-main\selectric_generator.py", line 40, in <module>
    mainMeshSet.load_new_mesh(filename)
pymeshlab.pmeshlab.PyMeshLabException: File does not exists: ballparts/0-0-0.STL`

Is there anything I'm doing wrong? Hope I can solve this. Very awesome project you've worked on here, I can't wait to try it on my machine.

**Comment by settinger** [comment]
Hi, thanks for trying out the repo! In the folder where the main .py file
is, can you try creating an empty directory named `ballparts`? I think
Python is trying to create a file in that directory, but it's unable to
create the directory itself.

**Comment by Niosquare** [comment]
Thank you for the response! The script is able to create the "ballparts" folder on its own, I deleted it, ran the script again, and it again made the folder but met with same error. I created it on my own one time, but to no avail. I think the .stl file mentioned in the error message, _0-0-0.STL_, corresponds to a character on the typeball, right? Thank you again for helping!

**Comment by settinger** [comment]
I see, so there's still some issue preventing it from generating and saving
the file 0-0-0.STL (which would be the character in the 0th column, 0th
row, and (iirc) lowercase). I'm traveling at the moment, wish I could help
you more but please keep me posted if you observe anything else!

**Comment by Hubcapp** [comment]
Works fine for me. This looks like a windows permissions error (you may need to move the project folder somewhere else, e.g. to C:\Users\YourName\Documents\selectric_typeballs).

**Comment by Niosquare** [comment]
Got it to work! Thank you so much guys! The work you've been doing on this project is amazing, it breathes some new life into the Selectric. Currently rendering Quadrivium NF! 

P.S I don't have a 3D printer to print these with, unfortunately. Is there any service I can use to outsource the printing? Thanks again!
