### ISSUE TITLE
Dimensions of blank ball are wrong, may damage typewriter

### ISSUE THREAD

**Issue by Hubcapp** [settinger/selectric_typeballs#3]
Hi, sorry to be alarmist, I love the idea of this project, however, it is currently unusable and dangerous due to the included STL file for the blank typeball having incorrect dimensions.

The dimensions are close enough that I was fooled into shaving it down a little and pressing it onto the spindle. The typeball I printed then went on, but it did not come off. Removing it as gently as I could was too violent of a force for the fragile head, and it has now put my Selectric II slightly out of alignment. This is perhaps a boneheaded move on my part, but I found evidence in <a href="https://www.youtube.com/watch?v=BLuB_FLSpTY">this repair video's youtube comments</a> that I am not the only idiot who excitedly pressed their newly printed slightly-too-small 3d typeball onto the spindle.

I believe that addressing issue #1 should be high priority for you, since as is, the hosted files supplied on Printables, as well as the blank STL included in this repo, will continue to disappoint, and damage the vintage equipment of those who actually try to print and use them.

**Comment by settinger** [comment]
Thanks for the info, I'll pull down the Shapeways links and put a warning on the Printables ones. I certainly don't want to damage any typewriters!

Can you tell me about the printer and resin you used to print the typeball? Was typeball height wrong, or the diameter of the spindle hole, or something else? I'll get issue #1 resolved now, though the parameters in the source file are still tuned for my printer and my resin (which apparently makes it too tight for others to print).

Best of luck re-aligning your Selectric!

**Comment by Hubcapp** [comment]
Hi, thanks for the quick response. 🙂

I used an Elegoo Saturn 2 resin printer with Siraya tech blu engineering resin. This resin is harder than other resins & ideal for mechanical applications such as 3D printed selectric type element. 🙂

My printing profile is calibrated, you can see a successful "Towns" print in the picture attached. You should definitely consider calibrating your print profile to an existing standard model instead of adjusting the 3D model to match.

In the moments before I tried to remove the ball, I was impressed that the printer does in fact have enough resolution to successfully type a very convincing floppy disk icon.

![signal-2023-07-06-133655_002](https://github.com/settinger/selectric_typeballs/assets/1337967/647ee272-d56a-4e3f-82bf-d19ea4ef85fc)

In researching realignment, I found out that there are over 800 different adjustments, and that an untrained person like myself can very quickly get it even worse out of alignment. I'll have to wait until I can get it back to a professional, but until then I have come to terms with the fact that my unit just has a bit of a wonky personality now.

**Comment by settinger** [comment]
The printer I used is a Formlabs 3B+ that is mostly used for validating biomedical devices; I assure you it is well calibrated :)

The typewriter that I tested on initially was a Model I Selectric, perhaps the spindle is a slightly different dimension? The fit was very good but not all the keys work on that machine so I can't use it consistently.

**Comment by Hubcapp** [comment]
Elements for I & II are the same, I think it should be the same dimensions on the spindle. 🤔

**Comment by Hubcapp** [comment]
I took a couple measurements, ⬇️👍📏

![signal-2023-07-06-171150_002](https://github.com/settinger/selectric_typeballs/assets/1337967/3ae5da87-d53d-4988-bad5-40006afd138a)
![signal-2023-07-06-171150_003](https://github.com/settinger/selectric_typeballs/assets/1337967/7d42413a-0157-4064-859d-0e5d168ef712)

**Comment by Hubcapp** [comment]
Thanks for posting the typeball_blank.scad source code. The 0.362 inch diameter measurement I took of that IBM type element, it looks like the radius should be about 4.60 mm, but BOSS_INNER_RAD is defined as 4.30 mm.

**Comment by Hubcapp** [comment]
![signal-2023-07-06-234615_002](https://github.com/settinger/selectric_typeballs/assets/1337967/8fa1f5c9-f3ee-4c6c-99e0-846e42326830)

It's actually maybe more complicated? The .362 is from dedent to dedent. There are 6 small dedents on the inside of the boss which are not actually modeled at all in the typeball and may have some use. I'm going to try just a larger radius but will report back on that.

**Comment by settinger** [comment]
Thank you for all the measurements and corrections in the PR! Dave Hayden of selectricrescue.org made some major improvements and created a version that works quite well in just OpenSCAD, without relying on external tools. You can get a copy of it here: https://selectricrescue.org/balls/SelectricElement88.scad

Dave also suggests:
> As for messing up the alignment, my guess is that they rotated or tilted the element which put slack in the corresponding tape and it fell off one of its pulleys. It's an easy fix, you tilt or rotate it again and guide the tape back onto the pulley and gently release the ball back to its neutral position. If that's what happened hopefully they didn't use it too much with the tape off and kink it up.
